image: docker-registry.ololoepepe.ru/node-openssl:8-alpine

services:
  - docker:dind

stages:
  - install
  - build
  - docker
  - deploy
  - push

variables:
  GIT_STRATEGY: none
  IMAGE_TAG: "$DOCKER_REGISTRY_HOST/selena4an/calculator:$CI_COMMIT_REF_NAME"

install:
  stage: install
  variables:
    GIT_STRATEGY: clone
  script:
    - 'wget -qO - https://sh.ololoepepe.ru/scripts/ci/gitlab/init-npm-registry.sh | sh -v'
    - npm install
  artifacts:
    name: "${CI_STAGE_NAME}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - etc/
      - node_modules/
      - src/
      - .babelrc
      - .dockerignore
      - Dockerfile
      - package.json

build:
  stage: build
  script:
    - npm run build
  dependencies:
    - install
  artifacts:
    name: "${CI_STAGE_NAME}_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - dist/
      - etc/
      - .dockerignore
      - Dockerfile

docker:
  image: docker-registry.ololoepepe.ru/docker-openssl:latest
  stage: docker
  dependencies:
    - build
  variables:
    GIT_STRATEGY: clone
  script:
    - 'wget -qO - https://sh.ololoepepe.ru/scripts/ci/gitlab/build-and-push-docker-image.sh | sh -v'

deploy_to_production:
  environment: production
  only:
    - master
  stage: deploy
  dependencies: []
  variables:
    APP_NAME: 'erenalysenko-com-calculator'
    SSH_HOST: "$PROD_SSH_HOST"
    SSH_PRIVATE_KEY: "$PROD_SSH_PRIVATE_KEY"
    SSH_USER: "$PROD_SSH_USER"
  script:
    - 'wget -O /deploy.sh https://sh.ololoepepe.ru/scripts/ci/gitlab/update-docker-image-and-restart-app.sh'
    - 'chmod +x /deploy.sh'
    - '/deploy.sh frontend'

push:
  image:
    name: 'alpine/git'
    entrypoint: [ "/bin/sh", "-c" ]
  only:
    - master
  stage: push
  dependencies:
    - build
  variables:
    GIT_STRATEGY: clone
  script:
    - git remote add github "$REMOTE_REPO_URL_GITHUB"
    - git push github master
